### ISSUE TITLE
Unable to import ecl2df

### ISSUE THREAD

**Issue by eivindsm** [equinor/ecl2df#37]
Under komodo bleeding3 I am unable to import the module :)
>>> import ecl2df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/res/komodo/bleeding3/root/lib/python3.6/site-packages/ecl2df/__init__.py", line 1, in <module>
    from .eclfiles import EclFiles
  File "/project/res/komodo/bleeding3/root/lib/python3.6/site-packages/ecl2df/eclfiles.py", line 11, in <module>
    import sunbeam.deck
ModuleNotFoundError: No module named 'sunbeam'

**Comment by berland** [comment]
A working sunbeam installation is a prerequisite for ecl2df.

**Comment by berland** [comment]
https://equinor.github.io/ecl2df/installation.html
