### ISSUE TITLE
Crash on RST loading

### ISSUE THREAD

**Issue by berland** [equinor/ecl2df#52]
```
$ ecl2csv grid --rstdate last  OSSJ-0.DATA
Traceback (most recent call last):
  File "/private/havb/venv/2.7.14/bin/ecl2csv", line 11, in <module>
    load_entry_point('ecl2df', 'console_scripts', 'ecl2csv')()
  File "/private/havb/projects/ecl2df/ecl2df/ecl2csv.py", line 105, in main
    args.func(args)
  File "/private/havb/projects/ecl2df/ecl2df/grid.py", line 431, in grid2df_main
    dropconstants=args.dropconstants,
  File "/private/havb/projects/ecl2df/ecl2df/grid.py", line 308, in df
    rst_df = rst2df(eclfiles, rstdates)
  File "/private/havb/projects/ecl2df/ecl2df/grid.py", line 157, in rst2df
    if eclfiles.get_rstfile().iget_named_kw(vec, rstindex):
  File "/project/res/komodo/2019.04.02/root/lib/python2.7/site-packages/ecl/eclfile/ecl_file.py", line 419, in iget_named_kw
    return self.global_view.iget_named_kw( kw_name , index )
  File "/project/res/komodo/2019.04.02/root/lib/python2.7/site-packages/ecl/eclfile/ecl_file_view.py", line 53, in iget_named_kw
    raise IndexError("Too large index: %d" % index)
IndexError: Too large index: 25
```

**Comment by berland** [comment]
(similar crash on resscript-version)
